#!/bin/bash

DTE() {
    dte="$(date +"%a, %B %d %l:%M%p"| sed 's/  / /g')"
    echo -e "$dte"
}

VOL() {

vol="$(amixer get Master | tail -n1 | sed -r 's/.*\[(.*)%\].*/\1/')"
    echo -e "墳 ${vol}%"
}

TEMP() {

    temp=$(sensors | grep "Core\ 0" |  awk '{print $3 }')
    echo -e " $temp"
}

WIFI() {

    wifi=$(cat /proc/net/wireless | awk '/wlp/ {print $4}' | tr -d ".")
    echo -e "說$wifi"
}


#
## ------------ Keyboard Layout
#K=$(xset q | grep LED | cut -d ":" -f4)
#  
#  
#if [ $K -eq "00000002" ] ; then
#          echo "En" ; echo "$delim"
#  else
#          echo "Fa" ; echo "$delim"
#fi
#
## ------------ Keyboard Layout
#
#

 while true; do
     xsetroot -name "$(VOL) | $(TEMP) | $(WIFI) | $(DTE) "
    sleep 30s    # Update time every minute
 done

